server:
  port: 8080

spring:
  profiles:
    active: dev
  output:
    ansi:
      enables: always

  jpa:
    open-in-view: false
    properties:
      hibernate:
        default_batch_fetch_size: 100

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 6000ms

  cloud:
    aws:
      s3:
        bucket: linkurator-bucket

custom:
  jwt:
    secret-key: abcdefghijklmnopqrstuvwxyz1234567890abcdefghijklmnopqrstuvwxyz1234567890
    expire-seconds: 80000
