name: Discord Notifications

on:
  pull_request:
    types: [opened]
  push:
    branches:
      - main

jobs:
  discordNotification:
    runs-on: ubuntu-latest

    steps:
    - name: Discord Github Notification when success
      if: success()
      uses: discord-actions/message@v2
      with:
        webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
        message: |
            🚀 New Pull Request Opened!
            **Title:** ${{ github.event.pull_request.title }}
            **Author:** ${{ github.event.pull_request.user.login }}
            **Link:** ${{ github.event.pull_request.html_url }}
            **Test:** ✅

    - name: Discord Github Notification when failure
      if: failure()
      uses: discord-actions/message@v2
      with:
        webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
        message: |
            🚀 New Pull Request Opened!
            **Title:** ${{ github.event.pull_request.title }}
            **Author:** ${{ github.event.pull_request.user.login }}
            **Link:** ${{ github.event.pull_request.html_url }}
            **Test:** ❌
