name: Backend CI

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  backend-ci:
    runs-on: ubuntu-latest
    steps:
      - name: 👋 Checkout
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 1

      - name: ☕️ Set up JDK 11
        uses: actions/setup-java@v4.7.0
        with:
          java-version: '21'
          
      - name: 🔐 Grant execute permission for gradlew
        run: chmod +x ./gradlew
        working-directory: backend/project2/
        shell: bash

      - name: 🛠 Build with Gradle with test profile
        run: sudo ./gradlew build -Pprofile=test
        working-directory: backend/project2/
        shell: bash
